### ISSUE TITLE
Is NUnit necessary in Nuget package?

### ISSUE THREAD

**Issue by joshka** [a-h/FakeDbSet#1]
Hi,
I can't see anything from NUnit used by InMemoryDbSet or DbSetHelper, but the package includes it as a dependency. Is this just used for the examples / unit tests and included in the package by mistake?

**Comment by a-h** [comment]
Yes, you're right, it's included as a dependency by mistake because "NuGet -pack" will pack up anything in the "packages.config" along with it and the FakeDbSet assembly had that included.  I'll rectify it.

Thanks!

**Comment by joshka** [comment]
Cheers, it looks like this is good as well.
