### ISSUE TITLE
Unit tests fail when VS 2012 is set to .net 4.0 and using EF 5.0

### ISSUE THREAD

**Issue by joshka** [a-h/FakeDbSet#2]
I have two projects a class library and a unit test project. Both have a reference to EF 5.0 and FakeDbSet via Nuget.
I am transitioning from VS 2010 to 2012, and hence need to run the projects as .Net 4.0.
For some reason, when I try and run the unit tests, the wrong version of EF tries to load, and this crashes with the following exception.

Test method TestingEfVersionIssue.UnitTests.UnitTest1.TestMethod1 threw exception: 
System.IO.FileLoadException: Could not load file or assembly 'EntityFramework, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    at TestingEfVersionIssue.Class1..ctor()
   at TestingEfVersionIssue.UnitTests.UnitTest1.TestMethod1() in UnitTest1.cs: line 12

Test class:

```
using Microsoft.VisualStudio.TestTools.UnitTesting;
namespace TestingEfVersionIssue.UnitTests
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var class1 = new Class1();
        }
    }
}
```

Tested classes:

```
namespace TestingEfVersionIssue
{
    public class Class1
    {
        public Class1()
        {
            var dbset = new FakeDbSet.InMemoryDbSet<Class2>();
        }
    }

    public class Class2
    {
    }
}
```

**Comment by joshka** [comment]
A workaround that seems to be appropriate for this is to use EF 4.3 until we can turn on .Net 4.5 for the projects.

**Comment by a-h** [comment]
It's a good point, the IDbSet interface resides in Entity Framework, so the test version has to have a reference to some version of EF.

One option is to use a binding redirect, there's an example here:

http://stackoverflow.com/questions/11749175/could-not-load-file-or-assembly-entityframework-after-downgrading-ef-5-0-0-0

Another option is just migrating the package to the EF5 NuGet dependency, which makes sense.  I've done that for all my work stuff, so I'm guessing most other developers have done this too.

**Comment by a-h** [comment]
I've upgraded the dependency to the EF 5 NuGet package, which should make it easy.

**Comment by joshka** [comment]
Thanks for the quick fix, will take a look tomorrow.

**Comment by joshka** [comment]
Thanks Adrian, I've just tested that this fixed the problem. All working well.
