### ISSUE TITLE
.AddOrUpdate() extension method fails

### ISSUE THREAD

**Issue by joshka** [a-h/FakeDbSet#3]
calling dbSet.AddOrUpdate(someEntity) fails with the following exception:

System.InvalidOperationException: Unable to call public, instance method AddOrUpdate on derived IDbSet<T> type 'FakeDbSet.InMemoryDbSet`1[FooBar]'. Method not found.

This is non-urgent for our uses. I'm recording it as an issue so that if I find a resolution / fix I've got a place to enter it.

**Comment by joshka** [comment]
From http://msdn.microsoft.com/en-us/library/hh846520(v=vs.103).aspx
"When the set parameter is a custom or fake IDbSet<TEntity> implementation, this method will attempt to locate and invoke a public, instance method with the same signature as this extension method."

It would be nice and fairly simple to implement this (will submit a pull request sometime soon).

**Comment by mathias-becher** [comment]
What is the current state of the issue?

A solution would be highly appreciated. If none is in the works, I will submit a pull request soon.

**Comment by joshka** [comment]
Hi Mathias,

I never progressed a solution. I haven't worked on an EF project in some time so this fell by the wayside. A solution would be something along the lines of the following (untested 1am code). Feel free to tackle this problem. 

```
class InMemoryDbSet<TEntity>
{
  public void AddOrUpdate(TEntity[] entities)
  {
    var newEntities = entities.Where(e => !Data.Contains(e));
    foreach (var entity in newEntities)
    {
      Add(entity);
    }
  }
  //...
}
```

Note: this doesn't handle identity semantics AFAIK, so you may be in a situation where it acts differently to the real thing. You could augment the InMemoryDbSet to correctly understand identity, but that's a bigger problem to tackle than this small one.

**Comment by a-h** [comment]
Personally, I've abandoned using FakeDbSet on new projects.  These days, I'm using the repository pattern to hide the EF implementation from other code and using integration tests for the EF code.  Test code setup can be quite lengthy with FakeDbSet.

**Comment by joshka** [comment]
A-h, perhaps stick an MIT license on the repo and mark it as up for grabs for someone else to takeover at will?

**Comment by aneves** [comment]
[Bumping the license suggestion.]

**Comment by joshka** [comment]
There's a pull request that adds the MIT license sitting ready for merge when you have a few seconds @a-h. https://github.com/a-h/FakeDbSet/pull/10
