### ISSUE TITLE
Static storage

### ISSUE THREAD

**Issue by joshka** [a-h/FakeDbSet#4]
When I started to use the InMemoryDbSet class, I was surprised by the use of static storage. This caused tests that pass when run individually to fail when run in bulk. I had to modify my setup methods to call the non-default constructor on the class to clear the storage on each call. (e.g. new InMemoryDbSet(true) for each DbSet in the fake context, and every time I need a specifically setup fake db set).

I like to write tests so that each test is isolated from each other. Static state means that I can't achieve this isolation by default.

Perhaps a nicer way to achieve the same shared state result would be to have a constructor that takes a HashSet<T> that can be stored statically in the calling test class if shared backing store is required.

**Comment by a-h** [comment]
Sounds like a good idea.  Something like https://github.com/a-h/FakeDbSet/commit/f40773ce4f631c1cb5f52699976edf4ccf7a9020
